DICE = {
    "de": {
        "articles": ["Der", "Die", "Das"],
        "d1": [
            "globale",
            "nationale",
            "geheime",
            "öff.-rechtliche",
            "außerirdische",
            "interdimensionale",
            "antifaschistische",
            "deutsche",
            "reichsdeutsche",
            "paramilitärische",
            "christliche",
            "muslimische",
            "reptilloide",
            "abendländische",
            "paneuropäische",
            "links-grüne",
            "satanistische",
            "unsichtbare",
            "konservative",
            "kommunistische",
        ],
        "d2": [
            "Finanz-",
            "Agrar-",
            "Auto-",
            "Pharma-",
            "Nuklear-",
            "Bolschewiken-",
            "Piloten-",
            "Alien-",
            "Medien-",
            "Transgender-",
            "Welt-",
            "Virologen-",
            "Freimaurer-",
            "Satanisten-",
            "Dunkelkraft-",
            "Vegetarier-",
            "UFO-",
            "Exil-",
            "Zauberer-",
            "Merkel-",
        ],
        "d3": [
            "Geheimdienst",
            "Vereinigung",
            "Lobby",
            "Organisation",
            "Sekte",
            "Loge",
            "Elite",
            "Regierung",
            "System",
            "Zelle",
            "Presse",
            "Kirche",
            "Verein",
            "Partei",
            "Gerichtshof",
            "Kommission",
            "Armee",
            "Theatergruppe",
            "Fußballmannschaft",
            "Bank",
        ],
        "d4": [
            "die Weltherrschaft",
            "die Auslöschung der Menschheit",
            "das Ersetzen aller Pronomen",
            "das vierte Reich",
            "die Zombie-Apokalypse",
            "die Singularität",
            "einen Kreuzzug",
            "die Abschaffung des Grundgesetzes",
            "die Besiedlung der Hohlerde",
            "einen riesigen Bankraub",
            "eine generelle Gehwegmaut",
            "die Klimakatastrophe",
            "einen Massenmord",
            "die erneute Kandidatur Trumps",
            "die Abschaffung des Internets",
            "einen globalen Stromausfall",
            "die Versklavung der Deutschen",
            "die Ermordung Attila Hildmanns",
            "die Abschaffung des Bargeldes",
            "die Reanimation der Dodos",
        ],
        "d5": [
            "Mikrowellenstrahlen",
            "Chemtrails",
            "Killerviren",
            "LSD im Trinkwasser",
            "Michael Wendler",
            "Kinderblut",
            "RFID-Chips",
            "Impfungen",
            "Außerirdische",
            "Geo-Engineering",
            "Windenergie",
            "Greta Thunberg",
            "Gedankenkontrolle",
            "der US Army",
            "Hypnose",
            "FFP2-Masken",
            "Netflix",
            "5G",
            "Nichtstun",
            "Bitcoins",
        ],
    },
    "en": {
        "articles": ["The"],
        "d1": [],
        "d2": [],
        "d3": [],
        "d4": [],
        "d5": [],
    },
}
