DICE = {
    "de": {
        "articles": ["Der", "Die", "Das"],
        "d1": [
            "globale",
            "nationale",
            "geheime",
            "öff.-rechtliche",
            "außerirdische",
            "interdimensionale",
            "antifaschistische",
            "deutsche",
            "reichsdeutsche",
            "paramilitärische",
            "christliche",
            "muslimische",
            "reptilloide",
            "abendländische",
            "paneuropäische",
            "links-grüne",
            "satanistische",
            "unsichtbare",
            "konservative",
            "kommunistische",
        ],
        "d2": [
            "Finanz-",
            "Agrar-",
            "Auto-",
            "Pharma-",
            "Nuklear-",
            "Bolschewiken-",
            "Piloten-",
            "Alien-",
            "Medien-",
            "Transgender-",
            "Welt-",
            "Virologen-",
            "Freimaurer-",
            "Satanisten-",
            "Dunkelkraft-",
            "Vegetarier-",
            "UFO-",
            "Exil-",
            "Zauberer-",
            "Merkel-",
        ],
        "d3": [
            "Geheimdienst",
            "Vereinigung",
            "Lobby",
            "Organisation",
            "Sekte",
            "Loge",
            "Elite",
            "Regierung",
            "System",
            "Zelle",
            "Presse",
            "Kirche",
            "Verein",
            "Partei",
            "Gerichtshof",
            "Kommission",
            "Armee",
            "Theatergruppe",
            "Fußballmannschaft",
            "Bank",
        ],
        "d4": [
            "die Weltherrschaft",
            "die Auslöschung der Menschheit",
            "das Ersetzen aller Pronomen",
            "das vierte Reich",
            "die Zombie-Apokalypse",
            "die Singularität",
            "einen Kreuzzug",
            "die Abschaffung des Grundgesetzes",
            "die Besiedlung der Hohlerde",
            "einen riesigen Bankraub",
            "eine generelle Gehwegmaut",
            "die Klimakatastrophe",
            "einen Massenmord",
            "die erneute Kandidatur Trumps",
            "die Abschaffung des Internets",
            "einen globalen Stromausfall",
            "die Versklavung der Deutschen",
            "die Ermordung Attila Hildmanns",
            "die Abschaffung des Bargeldes",
            "die Reanimation der Dodos",
        ],
        "d5": [
            "Mikrowellenstrahlen",
            "Chemtrails",
            "Killerviren",
            "LSD im Trinkwasser",
            "Michael Wendler",
            "Kinderblut",
            "RFID-Chips",
            "Impfungen",
            "Außerirdische",
            "Geo-Engineering",
            "Windenergie",
            "Greta Thunberg",
            "Gedankenkontrolle",
            "der US Army",
            "Hypnose",
            "FFP2-Masken",
            "Netflix",
            "5G",
            "Nichtstun",
            "Bitcoins",
        ],
    },
    "en": {
        "articles": ["The"],
        "d1": [
            "global",
            "national",
            "secret",
            "state-funded",
            "extraterrestrial",
            "interdimensional",
            "antifascist",
            "German",
            "Reich-German",
            "paramilitary",
            "Christian",
            "Muslim",
            "reptilian",
            "Western",
            "pan-European",
            "eco-leftist",
            "Satanic",
            "invisible",
            "conservative",
            "communist",
        ],
        "d2": [
            "Finance-",
            "Agri-",
            "Auto-",
            "Pharma-",
            "Nuclear-",
            "Bolshevist-",
            "Pilots'-",
            "Alien-",
            "Media-",
            "Transgender-",
            "World-",
            "Virologist-",
            "Freemason-",
            "Satanist-",
            "Dark-Force-",
            "Vegan-",
            "UFO-",
            "Exile-",
            "Sorcerer-",
            "Merkel-",
        ],
        "d3": [
            "Intelligence Service",
            "Association",
            "Lobby",
            "Organisation",
            "Cult",
            "Lodge",
            "Elite",
            "Government",
            "System",
            "Cell",
            "Press",
            "Church",
            "Club",
            "Party",
            "Tribunal",
            "Commission",
            "Army",
            "Theatre Troupe",
            "Football Club",
            "Bank",
        ],
        "d4": [
            "world domination",
            "the extinction of mankind",
            "the abolition of all pronouns",
            "the Fourth Reich",
            "the Zombie Apocalypse",
            "the Singularity",
            "a holy crusade",
            "the abolition of the constitution",
            "the colonisation of Hollow Earth",
            "a massive bank heist",
            "a mandatory pavement toll",
            "the climate catastrophe",
            "a mass murder",
            "Trump's third presidential run",
            "the abolition of the internet",
            "a global power blackout",
            "the enslavement of the Germans",
            "the assassination of Attila Hildmann",
            "the abolition of cash",
            "the reanimation of the Dodo",
        ],
        "d5": [
            "microwave radiation",
            "chemtrails",
            "killer viruses",
            "LSD in the water supply",
            "Michael Wendler",
            "children's blood",
            "RFID chips",
            "vaccinations",
            "extraterrestrials",
            "geo-engineering",
            "wind turbines",
            "Greta Thunberg",
            "mind control",
            "the US Army",
            "hypnosis",
            "FFP2 masks",
            "Netflix",
            "5G",
            "doing absolutely nothing",
            "Bitcoin",
        ],
    },
}
